### ISSUE TITLE
MockChannel: Overridden methods do not declare exceptions

### ISSUE THREAD

**Issue by joeltoby** [fridujo/rabbitmq-mock#102]
### Issue summary:

Methods in MockChannel which override Channel interface methods do not declare the same exceptions.  For example, `basicAck` does not declare an `IOException`:

Channel:
```
    void basicAck(long deliveryTag, boolean multiple) throws IOException;
```

MockChannel:
```
    @Override
    public void basicAck(long deliveryTag, boolean multiple) {
        getTransactionOrNode().basicAck(deliveryTag, multiple);
        metricsCollectorWrapper.basicAck(this, deliveryTag, multiple);
    }
```

### Why it matters:

Without the declared exceptions, it is not possible to mock throwing of the checked exception.  Example / use-case:

```
try(Channel channel = Mockito.spy(conn.createChannel())) {
  assertThat(channel).isInstanceOf(MockChannel.class);
  
  Mockito.doThrow(new IOException("ACK failed"))
    .when(channel)
    .basicAck(anyLong(), anyBoolean());
  
  // If the ACK fails (i.e. throws an IOException, my app will try 3 times.
  // This is the behaviour I want to test
  verify(channel, times(3)).basicAck(anyLong(), anyBoolean());
}
```

Due to the undeclared exception, this test results in an error:  `Checked exception is invalid for this method!`

### Is this a valid use case?

Is this a valid use-case, or am I using rabbitmq-mock incorrectly?

If its a valid issue, I'm happy to create a PR to fix it if that's OK?

**Comment by ledoyen** [comment]
Hello and thanks for your insterrest in this project !

I think your use-case is valid, but why use **rabbitmq-mock** for it ?

Can't you roll with amqp-client interfaces only ? Something like:
```java
Channel channel = Mockito.mock(Channel.class);  
Mockito.doThrow(new IOException("ACK failed"))
    .when(channel)
    .basicAck(anyLong(), anyBoolean());

  // trigger the application logic

verify(channel, times(3)).basicAck(anyLong(), anyBoolean());
```

Maybe I am missing your point though.

**Comment by joeltoby** [comment]
Thanks for the response / suggestion Loïc.  That's actually a really good point.  There is no reason for me not to just do it amqp-client interfaces!

The other tests for this component, required `rabbitmq-mock` so I just didn't think of not using it for this test.

**Comment by ledoyen** [comment]
I am glad that you do not have an issue after all.

However if you need to compose Mockito and rabbitmq-mock with spy for different scenarios, we can still change signatures.

I feel like there should be a way to inject this kind of behavior in rabbitmq-mock to trigger custom behavior based on specific exceptions. This could be useful to test recovery on error scenarios.

@joeltoby, I let you close the issue if you are okay with it.

**Comment by joeltoby** [comment]
@ledoyen - that sounds reasonable.  I'm happy to update the sigs if that helps (and then close the issue)?  If you'd prefer to leave it for now, I'll just close.

**Comment by ledoyen** [comment]
If you do not need it, just close :smile:
