### ISSUE TITLE
MetricCollector.consumedMessage is called incorrectly.

### ISSUE THREAD

**Issue by Yasushi** [fridujo/rabbitmq-mock#117]
In rabbitmq-java-client, consumedMessage is called before handleDelivery.

https://github.com/rabbitmq/rabbitmq-java-client/blob/v5.9.0/src/main/java/com/rabbitmq/client/impl/ChannelN.java#L452-L460

But in mock, consumedMessage is called after it.

https://github.com/fridujo/rabbitmq-mock/blob/1b162cb9947925ad69d594a1849c1fcf764a6606/src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java#L101-L102

**Comment by ledoyen** [comment]
Hi, thanks for reporting this.

This is indeed a bug.

**Comment by ledoyen** [comment]
@Yasushi this should be fixed in release **1.1.0**
