### ISSUE TITLE
MockQueue should not use declaring channel for metrics

### ISSUE THREAD

**Issue by RedMu** [fridujo/rabbitmq-mock#125]
When trying to use the MockConnectionFactory for integration tests for a Spring Boot application I noticed that metrics were not complete when using a transaction manager.  Upon further investigation I noticed MockQueue stores the MockChannel used to create it.  It subsequently uses this in deliverToConsumerIfPossible to register consumption.  

This means that acknowledgements are not recorded in AbstractMetricsCollector.updateChannelStateAfterAckReject for single messages because channelState.unackedMessageDeliveryTags does not contain the consumption, instead it was recorded against the channel used to declare the queue.

I've provided a PR with two commits.  The first provides a failing test, the second commit introduces a fix which stores the MockChannel in the ConsumerAndTag when basicConsume is called so it can be used when delivering to the consumer.

**Comment by ledoyen** [comment]
Merged #126.
