### ISSUE TITLE
RoutingKey does not follow spec for topic exchanges

### ISSUE THREAD

**Issue by mdiasribeiro** [fridujo/rabbitmq-mock#137]
When using a topic exchange, the official RMQ tutorial states that:
>  (hash) can substitute for zero or more words. (https://www.rabbitmq.com/tutorials/tutorial-five-python.html)

This means that a Queue bound to an Exchange with the RoutingKey '_something.#_' should be able to match a message with a RoutingKey '_something_'. This is, as expected, also the behavior on a real RMQ system. **On the mock however, the hash matches against 1 or more words (instead of 0 or more).** I believe the culprit is **MockTopicExchange.java:19**.
The correct behavior is useful because it allows for publishing routing keys to be modified with additional information in the future without breaking existing bindings.

**Comment by ledoyen** [comment]
Hi, thanks for spotting this.

Indeed the matching algorithm have been written during the earliest ages of the lib and needs to be improved.

**Comment by ledoyen** [comment]
@mdiasribeiro Could you confirm that new test cases are okay for you ?
https://github.com/fridujo/rabbitmq-mock/blob/cd010e713fe2a9c8c2d2459d4e0ee1d7e6c7a3c0/src/test/java/com/github/fridujo/rabbitmq/mock/exchange/ExchangeTest.java#L106-L116

https://github.com/fridujo/rabbitmq-mock/blob/cd010e713fe2a9c8c2d2459d4e0ee1d7e6c7a3c0/src/test/java/com/github/fridujo/rabbitmq/mock/exchange/ExchangeTest.java#L123-L137
Thanks in advance,

**Comment by mdiasribeiro** [comment]
They look fine to me
