### ISSUE TITLE
default exchange name is "default" instead of ""

### ISSUE THREAD

**Issue by madmuffin1** [fridujo/rabbitmq-mock#17]
When publishing a message to the default exchange using 

https://github.com/fridujo/rabbitmq-mock/blob/b78abc7005e0241eda5e583e015b9cfc4015191e/src/main/java/com/github/fridujo/rabbitmq/mock/exchange/MockDefaultExchange.java#L16-L19

the exchangeName is set to "default". According to the [documentation](https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchange-default) the name of the default exchange should be "".

A problem arose while setting up a test in a module of ours, where certain scenarios will cause a message to be re-published and acked. in this case, we take the Envelope.exchange property to determine which exchange to publish to.

rabbitmq-mock will then complain with a `java.lang.IllegalArgumentException: No exchange named default` error, since the default exchange key is correctly set to "".

https://github.com/fridujo/rabbitmq-mock/blob/2f5348f79bea8c27801af3039522abf492967d39/src/main/java/com/github/fridujo/rabbitmq/mock/MockNode.java#L27-L29

I suggest changing the static "default" in MockDefaultExchange to "".

**Comment by ledoyen** [comment]
Indeed, that is a bug.

Thanks for pointing this one up.

I will shortly apply a fix.

**Comment by ledoyen** [comment]
Fixed in version **1.0.6**
