### ISSUE TITLE
Unstable delivery in when more than one consumer is used

### ISSUE THREAD

**Issue by piotrwielgolaski-tomtom** [fridujo/rabbitmq-mock#289]
In my case I have 5 consumer register for queue, all works file in 90% of cases.
Occassionally it crash in MockQueue::deliverToConsumerIfPossible with NPE.
1/ NPE is not catch and whole delivery is broken
2/ map from https://github.com/fridujo/rabbitmq-mock/blob/e6971136c711efe0f6e822f19769f23b5a42dd4e/src/main/java/com/github/fridujo/rabbitmq/mock/MockQueue.java#L46 is unstable it say it has size 5, but in fact has less elements

I think (2) could be easier fixed with concurrent version of map.

**Comment by ledoyen** [comment]
Hello @piotrwielgolaski-tomtom , thank you for reporting this.

Could you provide a sample test that demonstrates the issue ? (even if it is flaky and should not fail most of the time)

Thank you !

**Comment by ledoyen** [comment]
Should be fixed with #318
