### ISSUE TITLE
Failed to declare queue

### ISSUE THREAD

**Issue by vencivenc** [fridujo/rabbitmq-mock#30]
Hello, 

I'm using spring boot version **2.1.2.RELEASE**, **amqp-client:5.4.3** and **rabbitmq-mock:1.0.9**.
When I try to mock the RabbitMQ Connection Factory like the showed example:
```
    @Bean
    public ConnectionFactory connectionFactory() {
        return new CachingConnectionFactory(MockConnectionFactoryFactory.build());
    }
```
I'm receiving error `org.springframework.amqp.rabbit.listener.BlockingQueueConsumer$DeclarationException: Failed to declare queue(s):[****(name of queue)]`

I was using this library with spring boot version **2.0.6.RELEASE** it was working perfect.

Can you please check it :)

**Comment by ledoyen** [comment]
Sure, I will take a look a soon as possible.
In the mean time, you can check with minimal setup if the issue you face can be reproduced with the integration project dedicated to spring-boot : https://github.com/fridujo/rabbitmq-mock/tree/master/src/it/spring_boot

**Comment by ledoyen** [comment]
I do not reproduce any errors with the versions you mentioned.
Here is the build log of the it/spring-boot integration project with the **v2.1.2.RELEASE** [build.log](https://github.com/fridujo/rabbitmq-mock/files/2773727/build.log)

You may have a way of interracting with **rabbitmq-mock** that is not convered yet, but I will need more data to reproduce it (stacktrace, sample code, etc.).

**Comment by vencivenc** [comment]
Hey @ledoyen, thank you for the fast response. 
I have created you a simple repo. You can check it here https://github.com/vencivenc/rabbitmq-mock-test
Also, I use JDK 11.0.2 osx x64

**Comment by ledoyen** [comment]
@vencivenc it seems that the error is related to how admin beans are declared.

Using such declaration `@Bean public List<Declarable> ...` will lead `applicationContext.getBeansOfType(Queue.class)` to return zero matching beans, even if there are beans of type `Queue` in the returned list.
This is exactly the code `RabbitAdmin#initialize` uses to create these queues that are declared through Spring javaConfig.

I have made you a PR to demonstrate a working solution.

So far, this issue appears to be related to how Spring *reads* configuration classes and not to a **rabbitmq-mock** bug.

Keep me posted if you do find however a bug in **rabbitmq-mock**.

**Comment by vencivenc** [comment]
Hey, @ledoyen. I cannot find the PR?

**Comment by ledoyen** [comment]
@vencivenc yes I created a patch through the website for the first time, and must have missed something.
The PR is now available https://github.com/vencivenc/rabbitmq-mock-test/pull/1/files

**Comment by vencivenc** [comment]
@ledoyen Thank you ! Everything works just perfect now. Really appreciate you help.
