### ISSUE TITLE
declaring exchange multiple times resets it

### ISSUE THREAD

**Issue by janssk1** [fridujo/rabbitmq-mock#34]
RMQ allows multiple parties to declare the same exchange. 

'exchange.declare' documentation in the AMQP spec: 

"This method creates an exchange if it does not already exist, and if the exchange exists, verifies that it is of the correct and expected class."

The mock implementation recreates the exchange on each declare, loosing all bindings.

**Comment by ledoyen** [comment]
Thanks for reporting this.

I will look into that as soon as possible.

**Comment by ledoyen** [comment]
A new release will be available soon.

**Comment by janssk1** [comment]
Thanks for the quick fix. Works like a charm!
