### ISSUE TITLE
Is this mock supported for Spring-Boot 1.5.x projects ?

### ISSUE THREAD

**Issue by saisurya-k** [fridujo/rabbitmq-mock#37]
I'm trying `rabbitmq-mock` for a spring boot **1.5.12** project built with **apache-camel**.
`amqp-client` version is 4.0.3 which is a supported version as per your documentation.
However when I tried to use this in my project(tried 1.0.10, 1.0.0 and 1.0.7), I got ClassNotFound exception in all cases, all those classes are from different versions of `com.rabbitmq:amqp-client`
Hence I would like to ask, whether this mock supports lower version of `amqp-client` ?
coz I saw that right from the beginning this library is using 2.x.x version of `spring-amqp`...

**Errors:**
java.lang.ClassNotFoundException: com.rabbitmq.client.DeliverCallback
java.lang.ClassNotFoundException: com.rabbitmq.client.QueueingConsumer

This is what I'm trying
```java
    @Bean
    public Channel amqpChannel() {
        Connection connection = new MockConnectionFactory().newConnection();
        Channel channel = null;
        try {
            channel = connection.createChannel();
            channel.exchangeDeclare("xyz", "direct", true);
        } catch (Exception e) {
            log.info("Error declaring xyz exchange");
        }

        return channel;
    }
```

**Comment by ledoyen** [comment]
Thanks for the feedback, the goal is indeed (among others) to support older versions **amqp-client**.

This may be a bug, I will look into it as soon as possible.

In the meantime, could you try using `MockConnectionFactoryFactory.build()` instead of `new MockConnectionFactory()` ?

**Comment by ledoyen** [comment]
Tested, and it worked, see https://github.com/fridujo/rabbitmq-mock/pull/38 for demo.

**Comment by saisurya-k** [comment]
Thanks a lot for quick response, will take a look and get back to you

**Comment by ledoyen** [comment]
Closing due to lack of feedback.
