### ISSUE TITLE
Any plans to support direct reply-to feature?

### ISSUE THREAD

**Issue by yuryfunikov** [fridujo/rabbitmq-mock#78]
More details here https://www.rabbitmq.com/direct-reply-to.html

**Comment by ledoyen** [comment]
Welcome and thanks for your interest in the project.

Yes. The purpose of this project is to be able to mimic as many features from RabbitMQ  as possible.

If you feel like it, you can make a PR about it.
If not, I can make itit a short delay (as it will require little time).

**Comment by yuryfunikov** [comment]
PR is ready https://github.com/fridujo/rabbitmq-mock/pull/82

**Comment by ledoyen** [comment]
Merged, see #82.
