### ISSUE TITLE
Backdoor to queues

### ISSUE THREAD

**Issue by asomov** [fridujo/rabbitmq-mock#87]
The test examples send and receive messages from the same queue. In practice often an application receives messages from one queue and sends them to another.
**Are there plans to implement direct access to the MockQueue and its messages ?**
Use case: application only sends messages to queue1. In the test run the code and check that the messages in MockQueue which mocks queue1 contain the expected content. 
(Scala, for instance, has a special backdoor _TestActorRef_ which gives direct access to the underlying actor and its mailbox.)

**Comment by ledoyen** [comment]
This is a good idea.

Initial design was to think of a routing system that allow testing even with a real RabbitMQ.
Something like specific routing-key ending up in a test-instance exclusive queue.

But if you need this, why not.
Is it ok if it is a read-only access ?

**Comment by asomov** [comment]
1. I think as the first step read-only is enough. I can try to help the develop and test
2. We will need write access for the use case when the application to test is listening to a queue and then in the test we can directly inject a message to MockNode instead of using standard RabbitMQ interface.
3. I do not think this project should work with the  real RabbitMQ. We have testcontiners for that.

**Comment by ledoyen** [comment]
@asomov `MockQueue` is now exposed by `MockChannel`.

However regarding point 2 I think that for now, publishing messages to queues is pretty straightforward with amqp-client API.

Regarding point 3, that is not what I meant. The purpose of this project is to supply a fast and testable mock of RabbitMQ. However by designing a system to be testable either with the mock or with a real implementation (through testcontainers or not), only one testing strategy have to be implemented thus reducing the complexity of the production code.

**Comment by ledoyen** [comment]
@asomov this should be available in release **1.1.0**
